#!/usr/bin/sh

./.fehbg 
pkill -USR1 -x sxhkd
sxhkd &
dunst &
fcitx5 -d --replace
~/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc config focused_border_color '#f4dbd6'
bspc config normal_border_color '#1e2030'
bspc config urgent_border_color '#f5a97f'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# localectl set-x11-keymap '' '' '' caps:ctrl_modifier
xinput set-prop "MSFT0001:00 04F3:31EF Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "MSFT0001:00 04F3:31EF Touchpad" "libinput Natural Scrolling Enabled" 1


